// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class CartMinhLk
{
    public int CartId { get; set; }

    public int? UserId { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CartItemMinhLk> CartItemMinhLks { get; set; } = new List<CartItemMinhLk>();

    public virtual User User { get; set; }
}