// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class CategoriesTanTm
{
    public int CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? ParentId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CategoriesTanTm> InverseParent { get; set; } = new List<CategoriesTanTm>();

    public virtual CategoriesTanTm Parent { get; set; }

    public virtual ICollection<ProductsTanTm> ProductsTanTms { get; set; } = new List<ProductsTanTm>();
}