// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class Preorder
{
    public int PreorderId { get; set; }

    public int? OrderId { get; set; }

    public decimal? DepositAmount { get; set; }

    public DateTime? ExpectedArrivalDate { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual OrdersNamNh Order { get; set; }

    public virtual ICollection<PreorderEvent> PreorderEvents { get; set; } = new List<PreorderEvent>();
}