// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class ProductMediaVanNb
{
    public int MediaId { get; set; }

    public int? VariantId { get; set; }

    public int? ProductId { get; set; }

    public string MediaUrl { get; set; }

    public string MediaType { get; set; }

    public int? SortOrder { get; set; }

    public virtual ProductsTanTm Product { get; set; }

    public virtual ProductVariantsVanNb Variant { get; set; }
}