// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class ProductsTanTm
{
    public int ProductId { get; set; }

    public int? CategoryId { get; set; }

    public int? BrandId { get; set; }

    public string Name { get; set; }

    public string ProductType { get; set; }

    public string ProductCode { get; set; }

    public string ShortDescription { get; set; }

    public string Description { get; set; }

    public decimal? BasePrice { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsFeatured { get; set; }

    public decimal? RatingAvg { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual BrandsTanTm Brand { get; set; }

    public virtual CategoriesTanTm Category { get; set; }

    public virtual ICollection<ProductMediaVanNb> ProductMediaVanNbs { get; set; } = new List<ProductMediaVanNb>();

    public virtual ICollection<ProductReviewsVanNb> ProductReviewsVanNbs { get; set; } = new List<ProductReviewsVanNb>();

    public virtual ICollection<ProductVariantsVanNb> ProductVariantsVanNbs { get; set; } = new List<ProductVariantsVanNb>();
}