// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class ProductVariantsVanNb
{
    public int VariantId { get; set; }

    public int? ProductId { get; set; }

    public string Color { get; set; }

    public string Material { get; set; }

    public string SizeLabel { get; set; }

    public string Sku { get; set; }

    public string Gender { get; set; }

    public decimal? UnitPrice { get; set; }

    public int? WeightGrams { get; set; }

    public bool? IsPreorder { get; set; }

    public DateTime? PreorderEtaDate { get; set; }

    public int? SoldCount { get; set; }

    public string PredictorEyeData { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CartItemMinhLk> CartItemMinhLks { get; set; } = new List<CartItemMinhLk>();

    public virtual ICollection<InventoryVanNb> InventoryVanNbs { get; set; } = new List<InventoryVanNb>();

    public virtual ICollection<OrderDetailNamNh> OrderDetailNamNhs { get; set; } = new List<OrderDetailNamNh>();

    public virtual ProductsTanTm Product { get; set; }

    public virtual ICollection<ProductMediaVanNb> ProductMediaVanNbs { get; set; } = new List<ProductMediaVanNb>();
}