// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class ShippingNhatM
{
    public int ShippingId { get; set; }

    public int? OrderId { get; set; }

    public string ShippingMethod { get; set; }

    public decimal? ShippingFee { get; set; }

    public string Status { get; set; }

    public string TrackingNumber { get; set; }

    public string Carrier { get; set; }

    public string ShippingNote { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual OrdersNamNh Order { get; set; }

    public virtual ICollection<TrackingEventNhatM> TrackingEventNhatMs { get; set; } = new List<TrackingEventNhatM>();
}