// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class VouchersTanTm
{
    public int VoucherId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public decimal? DiscountAmount { get; set; }

    public int? DiscountPercent { get; set; }

    public decimal? MinOrderValue { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? UsageLimit { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<OrdersNamNh> OrdersNamNhs { get; set; } = new List<OrdersNamNh>();
}