// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class InventoryVanNb
{
    public int InventoryId { get; set; }

    public int? VariantId { get; set; }

    public int? QuantityOnHand { get; set; }

    public int? Reserved { get; set; }

    public int? ReorderLevel { get; set; }

    public string WarehouseLocation { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ProductVariantsVanNb Variant { get; set; }
}