// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class PrescriptionTanBn
{
    public int PrescriptionId { get; set; }

    public int? UserId { get; set; }

    public int? VerifiedByStaffId { get; set; }

    public string VerifyStatus { get; set; }

    public decimal? PdMm { get; set; }

    public string ImageUrl { get; set; }

    public string Note { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<PrescriptionEyeDetailsTanBn> PrescriptionEyeDetailsTanBns { get; set; } = new List<PrescriptionEyeDetailsTanBn>();

    public virtual User User { get; set; }

    public virtual User VerifiedByStaff { get; set; }
}