// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class PrescriptionEyeDetailsTanBn
{
    public int DetailId { get; set; }

    public int? PrescriptionId { get; set; }

    public string EyeSide { get; set; }

    public decimal? Sph { get; set; }

    public decimal? Cyl { get; set; }

    public int? Axis { get; set; }

    public decimal? Prism { get; set; }

    public string BaseDirection { get; set; }

    public decimal? AddPower { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual PrescriptionTanBn Prescription { get; set; }
}