// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class TrackingEventNhatM
{
    public int TrackingEventId { get; set; }

    public int? ShippingId { get; set; }

    public DateTime? EventTime { get; set; }

    public string Status { get; set; }

    public string Location { get; set; }

    public string Note { get; set; }

    public string RawData { get; set; }

    public virtual ShippingNhatM Shipping { get; set; }
}