// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class ReturnRequest
{
    public int ReturnId { get; set; }

    public int? OrderId { get; set; }

    public int? UserId { get; set; }

    public string Status { get; set; }

    public string ReasonCode { get; set; }

    public string Description { get; set; }

    public DateTime? RequestedAt { get; set; }

    public int? ApprovedByStaffId { get; set; }

    public DateTime? RefundedAt { get; set; }

    public DateTime? ClosedAt { get; set; }

    public virtual OrdersNamNh Order { get; set; }

    public virtual User User { get; set; }
}