// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
namespace glassStore.Entites.NamNH.Models;

public partial class glass_StoreContext : DbContext
{
    public glass_StoreContext(DbContextOptions<glass_StoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BrandsTanTm> BrandsTanTms { get; set; }

    public virtual DbSet<CartItemMinhLk> CartItemMinhLks { get; set; }

    public virtual DbSet<CartMinhLk> CartMinhLks { get; set; }

    public virtual DbSet<CategoriesTanTm> CategoriesTanTms { get; set; }

    public virtual DbSet<InventoryVanNb> InventoryVanNbs { get; set; }

    public virtual DbSet<OrderDetailNamNh> OrderDetailNamNhs { get; set; }

    public virtual DbSet<OrdersNamNh> OrdersNamNhs { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Preorder> Preorders { get; set; }

    public virtual DbSet<PreorderEvent> PreorderEvents { get; set; }

    public virtual DbSet<PrescriptionEyeDetailsTanBn> PrescriptionEyeDetailsTanBns { get; set; }

    public virtual DbSet<PrescriptionTanBn> PrescriptionTanBns { get; set; }

    public virtual DbSet<ProductMediaVanNb> ProductMediaVanNbs { get; set; }

    public virtual DbSet<ProductReviewsVanNb> ProductReviewsVanNbs { get; set; }

    public virtual DbSet<ProductVariantsVanNb> ProductVariantsVanNbs { get; set; }

    public virtual DbSet<ProductsTanTm> ProductsTanTms { get; set; }

    public virtual DbSet<ReturnRequest> ReturnRequests { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ShippingNhatM> ShippingNhatMs { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<TrackingEventNhatM> TrackingEventNhatMs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<VouchersTanTm> VouchersTanTms { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BrandsTanTm>(entity =>
        {
            entity.HasKey(e => e.BrandId).HasName("PK__Brands_T__5E5A8E272DC5F2EA");

            entity.ToTable("Brands_TanTM");

            entity.Property(e => e.BrandId).HasColumnName("brand_id");
            entity.Property(e => e.Country)
                .HasMaxLength(50)
                .HasColumnName("country");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Slug)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("slug");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<CartItemMinhLk>(entity =>
        {
            entity.HasKey(e => e.CartItemId).HasName("PK__Cart_Ite__5D9A6C6EE6B4AB22");

            entity.ToTable("Cart_Item_MinhLK");

            entity.Property(e => e.CartItemId).HasColumnName("cart_item_id");
            entity.Property(e => e.AddedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("added_at");
            entity.Property(e => e.CartId).HasColumnName("cart_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.UnitPriceSnapshot)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("unit_price_snapshot");
            entity.Property(e => e.VariantId).HasColumnName("variant_id");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItemMinhLks)
                .HasForeignKey(d => d.CartId)
                .HasConstraintName("FK__Cart_Item__cart___01142BA1");

            entity.HasOne(d => d.Variant).WithMany(p => p.CartItemMinhLks)
                .HasForeignKey(d => d.VariantId)
                .HasConstraintName("FK__Cart_Item__varia__02084FDA");
        });

        modelBuilder.Entity<CartMinhLk>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__Cart_Min__2EF52A271E761C06");

            entity.ToTable("Cart_MinhLK");

            entity.Property(e => e.CartId).HasColumnName("cart_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.ExpiresAt)
                .HasColumnType("datetime")
                .HasColumnName("expires_at");
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .HasColumnName("note");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.CartMinhLks)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Cart_Minh__user___7D439ABD");
        });

        modelBuilder.Entity<CategoriesTanTm>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__D54EE9B4BF981CBE");

            entity.ToTable("Categories_TanTM");

            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK__Categorie__paren__571DF1D5");
        });

        modelBuilder.Entity<InventoryVanNb>(entity =>
        {
            entity.HasKey(e => e.InventoryId).HasName("PK__Inventor__B59ACC49004780BD");

            entity.ToTable("Inventory_VanNB");

            entity.Property(e => e.InventoryId).HasColumnName("inventory_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.QuantityOnHand)
                .HasDefaultValue(0)
                .HasColumnName("quantity_on_hand");
            entity.Property(e => e.ReorderLevel).HasColumnName("reorder_level");
            entity.Property(e => e.Reserved)
                .HasDefaultValue(0)
                .HasColumnName("reserved");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.VariantId).HasColumnName("variant_id");
            entity.Property(e => e.WarehouseLocation)
                .HasMaxLength(100)
                .HasColumnName("warehouse_location");

            entity.HasOne(d => d.Variant).WithMany(p => p.InventoryVanNbs)
                .HasForeignKey(d => d.VariantId)
                .HasConstraintName("FK__Inventory__varia__73BA3083");
        });

        modelBuilder.Entity<OrderDetailNamNh>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Order_De__3213E83FC09B7DC9");

            entity.ToTable("Order_Detail_NamNH");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.LineTotal)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("line_total");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.ProductNameSnapshot)
                .HasMaxLength(200)
                .HasColumnName("product_name_snapshot");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.UnitPriceAtPurchase)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("unit_price_at_purchase");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.VariantDescSnapshot)
                .HasMaxLength(200)
                .HasColumnName("variant_desc_snapshot");
            entity.Property(e => e.VariantId).HasColumnName("variant_id");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetailNamNhs)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__Order_Det__order__0B91BA14");

            entity.HasOne(d => d.Variant).WithMany(p => p.OrderDetailNamNhs)
                .HasForeignKey(d => d.VariantId)
                .HasConstraintName("FK__Order_Det__varia__0C85DE4D");
        });

        modelBuilder.Entity<OrdersNamNh>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders_N__46596229F5DBFFF4");

            entity.ToTable("Orders_NamNH");

            entity.HasIndex(e => e.OrderCode, "UQ__Orders_N__99D12D3F248B6065").IsUnique();

            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerNote).HasColumnName("customer_note");
            entity.Property(e => e.DiscountTotal)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("discount_total");
            entity.Property(e => e.GrandTotal)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("grand_total");
            entity.Property(e => e.OrderCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("order_code");
            entity.Property(e => e.OrderType)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("order_type");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("payment_method");
            entity.Property(e => e.ReceiverAddress)
                .HasMaxLength(255)
                .HasColumnName("receiver_address");
            entity.Property(e => e.ReceiverName)
                .HasMaxLength(100)
                .HasColumnName("receiver_name");
            entity.Property(e => e.ReceiverPhone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("receiver_phone");
            entity.Property(e => e.ShippingFee)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("shipping_fee");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.Subtotal)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("subtotal");
            entity.Property(e => e.TaxTotal)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("tax_total");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");

            entity.HasOne(d => d.User).WithMany(p => p.OrdersNamNhs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Orders_Na__user___06CD04F7");

            entity.HasOne(d => d.Voucher).WithMany(p => p.OrdersNamNhs)
                .HasForeignKey(d => d.VoucherId)
                .HasConstraintName("FK__Orders_Na__vouch__07C12930");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__ED1FC9EAE3477FB6");

            entity.Property(e => e.PaymentId).HasColumnName("payment_id");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.BankCode)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("bank_code");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.GatewayTransactionId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("gateway_transaction_id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.PaidAt)
                .HasColumnType("datetime")
                .HasColumnName("paid_at");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("payment_method");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.TransactionCode)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("transaction_code");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Order).WithMany(p => p.Payments)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__Payments__order___10566F31");
        });

        modelBuilder.Entity<Preorder>(entity =>
        {
            entity.HasKey(e => e.PreorderId).HasName("PK__Preorder__C55A531A4BA9D092");

            entity.ToTable("Preorder");

            entity.Property(e => e.PreorderId).HasColumnName("preorder_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DepositAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("deposit_amount");
            entity.Property(e => e.ExpectedArrivalDate)
                .HasColumnType("datetime")
                .HasColumnName("expected_arrival_date");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Order).WithMany(p => p.Preorders)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__Preorder__order___2739D489");
        });

        modelBuilder.Entity<PreorderEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__Preorder__2370F727E9D430FC");

            entity.ToTable("Preorder_Event");

            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.EventType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("event_type");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.PreorderId).HasColumnName("preorder_id");

            entity.HasOne(d => d.Preorder).WithMany(p => p.PreorderEvents)
                .HasForeignKey(d => d.PreorderId)
                .HasConstraintName("FK__Preorder___preor__2B0A656D");
        });

        modelBuilder.Entity<PrescriptionEyeDetailsTanBn>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__Prescrip__38E9A22493D59A31");

            entity.ToTable("Prescription_Eye_Details_TanBN");

            entity.Property(e => e.DetailId).HasColumnName("detail_id");
            entity.Property(e => e.AddPower)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("add_power");
            entity.Property(e => e.Axis).HasColumnName("axis");
            entity.Property(e => e.BaseDirection)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("base_direction");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Cyl)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("cyl");
            entity.Property(e => e.EyeSide)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("eye_side");
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .HasColumnName("note");
            entity.Property(e => e.PrescriptionId).HasColumnName("prescription_id");
            entity.Property(e => e.Prism)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("prism");
            entity.Property(e => e.Sph)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("sph");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Prescription).WithMany(p => p.PrescriptionEyeDetailsTanBns)
                .HasForeignKey(d => d.PrescriptionId)
                .HasConstraintName("FK__Prescript__presc__1F98B2C1");
        });

        modelBuilder.Entity<PrescriptionTanBn>(entity =>
        {
            entity.HasKey(e => e.PrescriptionId).HasName("PK__Prescrip__3EE444F834E49DA7");

            entity.ToTable("Prescription_TanBN");

            entity.Property(e => e.PrescriptionId).HasColumnName("prescription_id");
            entity.Property(e => e.CompletedAt)
                .HasColumnType("datetime")
                .HasColumnName("completed_at");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("image_url");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.PdMm)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("pd_mm");
            entity.Property(e => e.StartedAt)
                .HasColumnType("datetime")
                .HasColumnName("started_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.VerifiedByStaffId).HasColumnName("verified_by_staff_id");
            entity.Property(e => e.VerifyStatus)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("verify_status");

            entity.HasOne(d => d.User).WithMany(p => p.PrescriptionTanBnUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Prescript__user___1AD3FDA4");

            entity.HasOne(d => d.VerifiedByStaff).WithMany(p => p.PrescriptionTanBnVerifiedByStaffs)
                .HasForeignKey(d => d.VerifiedByStaffId)
                .HasConstraintName("FK__Prescript__verif__1BC821DD");
        });

        modelBuilder.Entity<ProductMediaVanNb>(entity =>
        {
            entity.HasKey(e => e.MediaId).HasName("PK__Product___D0A840F43993D481");

            entity.ToTable("Product_Media_VanNB");

            entity.Property(e => e.MediaId).HasColumnName("media_id");
            entity.Property(e => e.MediaType)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("media_type");
            entity.Property(e => e.MediaUrl)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("media_url");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.SortOrder).HasColumnName("sort_order");
            entity.Property(e => e.VariantId).HasColumnName("variant_id");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductMediaVanNbs)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__Product_M__produ__6E01572D");

            entity.HasOne(d => d.Variant).WithMany(p => p.ProductMediaVanNbs)
                .HasForeignKey(d => d.VariantId)
                .HasConstraintName("FK__Product_M__varia__6D0D32F4");
        });

        modelBuilder.Entity<ProductReviewsVanNb>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Product___60883D90AC70942C");

            entity.ToTable("Product_Reviews_VanNB");

            entity.Property(e => e.ReviewId).HasColumnName("review_id");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductReviewsVanNbs)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__Product_R__produ__797309D9");

            entity.HasOne(d => d.User).WithMany(p => p.ProductReviewsVanNbs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Product_R__user___787EE5A0");
        });

        modelBuilder.Entity<ProductVariantsVanNb>(entity =>
        {
            entity.HasKey(e => e.VariantId).HasName("PK__Product___EACC68B7B417769D");

            entity.ToTable("Product_Variants_VanNB");

            entity.HasIndex(e => e.Sku, "UQ__Product___DDDF4BE777D2CE65").IsUnique();

            entity.Property(e => e.VariantId).HasColumnName("variant_id");
            entity.Property(e => e.Color)
                .HasMaxLength(50)
                .HasColumnName("color");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Gender)
                .HasMaxLength(20)
                .HasColumnName("gender");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsPreorder)
                .HasDefaultValue(false)
                .HasColumnName("is_preorder");
            entity.Property(e => e.Material)
                .HasMaxLength(50)
                .HasColumnName("material");
            entity.Property(e => e.PredictorEyeData).HasColumnName("predictor_eye_data");
            entity.Property(e => e.PreorderEtaDate)
                .HasColumnType("datetime")
                .HasColumnName("preorder_eta_date");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.SizeLabel)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("size_label");
            entity.Property(e => e.Sku)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("sku");
            entity.Property(e => e.SoldCount)
                .HasDefaultValue(0)
                .HasColumnName("sold_count");
            entity.Property(e => e.UnitPrice)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("unit_price");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.WeightGrams).HasColumnName("weight_grams");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductVariantsVanNbs)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__Product_V__produ__6A30C649");
        });

        modelBuilder.Entity<ProductsTanTm>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__47027DF5D4465D26");

            entity.ToTable("Products_TanTM");

            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.BasePrice)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("base_price");
            entity.Property(e => e.BrandId).HasColumnName("brand_id");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsFeatured)
                .HasDefaultValue(false)
                .HasColumnName("is_featured");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");
            entity.Property(e => e.ProductCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("product_code");
            entity.Property(e => e.ProductType)
                .HasMaxLength(50)
                .HasColumnName("product_type");
            entity.Property(e => e.RatingAvg)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(3, 2)")
                .HasColumnName("rating_avg");
            entity.Property(e => e.ShortDescription)
                .HasMaxLength(500)
                .HasColumnName("short_description");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Brand).WithMany(p => p.ProductsTanTms)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK__Products___brand__628FA481");

            entity.HasOne(d => d.Category).WithMany(p => p.ProductsTanTms)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__Products___categ__619B8048");
        });

        modelBuilder.Entity<ReturnRequest>(entity =>
        {
            entity.HasKey(e => e.ReturnId).HasName("PK__Return_R__35C234735DAFE710");

            entity.ToTable("Return_Request");

            entity.Property(e => e.ReturnId).HasColumnName("return_id");
            entity.Property(e => e.ApprovedByStaffId).HasColumnName("approved_by_staff_id");
            entity.Property(e => e.ClosedAt)
                .HasColumnType("datetime")
                .HasColumnName("closed_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.ReasonCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("reason_code");
            entity.Property(e => e.RefundedAt)
                .HasColumnType("datetime")
                .HasColumnName("refunded_at");
            entity.Property(e => e.RequestedAt)
                .HasColumnType("datetime")
                .HasColumnName("requested_at");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Order).WithMany(p => p.ReturnRequests)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__Return_Re__order__22751F6C");

            entity.HasOne(d => d.User).WithMany(p => p.ReturnRequests)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Return_Re__user___236943A5");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__760965CC72403679");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<ShippingNhatM>(entity =>
        {
            entity.HasKey(e => e.ShippingId).HasName("PK__Shipping__059B15A9EBF5B925");

            entity.ToTable("Shipping_NhatM");

            entity.Property(e => e.ShippingId).HasColumnName("shipping_id");
            entity.Property(e => e.Carrier)
                .HasMaxLength(100)
                .HasColumnName("carrier");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DeliveredAt)
                .HasColumnType("datetime")
                .HasColumnName("delivered_at");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.ShippingFee)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("shipping_fee");
            entity.Property(e => e.ShippingMethod)
                .HasMaxLength(100)
                .HasColumnName("shipping_method");
            entity.Property(e => e.ShippingNote).HasColumnName("shipping_note");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.TrackingNumber)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("tracking_number");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Order).WithMany(p => p.ShippingNhatMs)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__Shipping___order__14270015");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TrackingEventNhatM>(entity =>
        {
            entity.HasKey(e => e.TrackingEventId).HasName("PK__Tracking__9F0B426E05C1723F");

            entity.ToTable("Tracking_Event_NhatM");

            entity.Property(e => e.TrackingEventId).HasColumnName("tracking_event_id");
            entity.Property(e => e.EventTime)
                .HasColumnType("datetime")
                .HasColumnName("event_time");
            entity.Property(e => e.Location)
                .HasMaxLength(200)
                .HasColumnName("location");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.RawData).HasColumnName("raw_data");
            entity.Property(e => e.ShippingId).HasColumnName("shipping_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");

            entity.HasOne(d => d.Shipping).WithMany(p => p.TrackingEventNhatMs)
                .HasForeignKey(d => d.ShippingId)
                .HasConstraintName("FK__Tracking___shipp__17036CC0");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__B9BE370FBA84E0FC");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__AB6E6164F4D73397").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DateOfBirth)
                .HasColumnType("datetime")
                .HasColumnName("date_of_birth");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .HasColumnName("full_name");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("phone_number");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__User__role_id__4E88ABD4");
        });

        modelBuilder.Entity<VouchersTanTm>(entity =>
        {
            entity.HasKey(e => e.VoucherId).HasName("PK__Vouchers__80B6FFA84E9E769B");

            entity.ToTable("Vouchers_TanTM");

            entity.HasIndex(e => e.Code, "UQ__Vouchers__357D4CF917088B58").IsUnique();

            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("code");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.DiscountAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("discount_amount");
            entity.Property(e => e.DiscountPercent).HasColumnName("discount_percent");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.MinOrderValue)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("min_order_value");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("start_date");
            entity.Property(e => e.UsageLimit).HasColumnName("usage_limit");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}