// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class CartItemMinhLk
{
    public int CartItemId { get; set; }

    public int? CartId { get; set; }

    public int? VariantId { get; set; }

    public int? Quantity { get; set; }

    public decimal? UnitPriceSnapshot { get; set; }

    public DateTime? AddedAt { get; set; }

    public virtual CartMinhLk Cart { get; set; }

    public virtual ProductVariantsVanNb Variant { get; set; }
}