// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class OrderDetailNamNh
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? VariantId { get; set; }

    public int? Quantity { get; set; }

    public string ProductNameSnapshot { get; set; }

    public string VariantDescSnapshot { get; set; }

    public decimal? UnitPriceAtPurchase { get; set; }

    public decimal? LineTotal { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual OrdersNamNh Order { get; set; }

    public virtual ProductVariantsVanNb Variant { get; set; }
}