// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class OrdersNamNh
{
    public int OrderId { get; set; }

    public int? UserId { get; set; }

    public int? VoucherId { get; set; }

    public string OrderType { get; set; }

    public string OrderCode { get; set; }

    public string PaymentMethod { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? DiscountTotal { get; set; }

    public decimal? TaxTotal { get; set; }

    public decimal? ShippingFee { get; set; }

    public decimal? GrandTotal { get; set; }

    public string Status { get; set; }

    public string CustomerNote { get; set; }

    public string ReceiverName { get; set; }

    public string ReceiverPhone { get; set; }

    public string ReceiverAddress { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<OrderDetailNamNh> OrderDetailNamNhs { get; set; } = new List<OrderDetailNamNh>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Preorder> Preorders { get; set; } = new List<Preorder>();

    public virtual ICollection<ReturnRequest> ReturnRequests { get; set; } = new List<ReturnRequest>();

    public virtual ICollection<ShippingNhatM> ShippingNhatMs { get; set; } = new List<ShippingNhatM>();

    public virtual User User { get; set; }

    public virtual VouchersTanTm Voucher { get; set; }
}