// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class PreorderEvent
{
    public int EventId { get; set; }

    public int? PreorderId { get; set; }

    public string EventType { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Preorder Preorder { get; set; }
}