// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace glassStore.Entites.NamNH.Models;

public partial class User
{
    public int UserId { get; set; }

    public int? RoleId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public bool? Status { get; set; }

    public string Address { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CartMinhLk> CartMinhLks { get; set; } = new List<CartMinhLk>();

    public virtual ICollection<OrdersNamNh> OrdersNamNhs { get; set; } = new List<OrdersNamNh>();

    public virtual ICollection<PrescriptionTanBn> PrescriptionTanBnUsers { get; set; } = new List<PrescriptionTanBn>();

    public virtual ICollection<PrescriptionTanBn> PrescriptionTanBnVerifiedByStaffs { get; set; } = new List<PrescriptionTanBn>();

    public virtual ICollection<ProductReviewsVanNb> ProductReviewsVanNbs { get; set; } = new List<ProductReviewsVanNb>();

    public virtual ICollection<ReturnRequest> ReturnRequests { get; set; } = new List<ReturnRequest>();

    public virtual Role Role { get; set; }
}